<?php
/**
 * @category    Lyonscg
 * @package     Lyonscg_CacheWarmer
 * @copyright   Copyright (c) 2013 Lyons Consulting Group (www.lyonscg.com)
 * @author      Richard Loerzel (rloerzel@lyonscg.com)
 */
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Additional Cache Management') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanImagesUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Catalog Images Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated product images files.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getUrl('*/*/cleanMedia');?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush JavaScript/CSS Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Themes JavaScript and CSS files combined to one file.')?>
        </td>
    </tr>    
     <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo Mage::helper("adminhtml")->getUrl('cachewarmer/adminhtml_cache/reheat'); ?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Warm Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Cycle through all product and catalog URLs to preload page content into cache.')?>
        </td>
    </tr>
</table>
<?php echo $this->getChildHtml(); ?>
