<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>

<div class="block delivery-date-block">
    <?php echo $this->getChildHtml('newsubscription.delivery_date') ?>
</div>


<div class="block summary-block" id="newsubscription_summary">
<?php echo $this->getChildHtml('newsubscription.summary') ?>
</div>

