<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
$subscription = $this->getSubscription();
?>
<div class="box-padding">
	 <div class="field">
        <label for="delivery_date"><?php echo $this->__('Your first delivery will be shipped on:') ?></label>
        <div class="input-box">
            <input type="text" id="delivery_date" name="delivery_date" value="<?php echo $subscription->getNextOrderDateText() ?>" title="<?php echo $this->__('Your first delivery will be shipped on:') ?>" class="input-text" />
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    $j(function(){
        $j("#delivery_date").datepicker({
            minDate: "+2",
            showOn: "both",
            buttonImage: "<?php echo $this->getSkinUrl('images/autoship/calendar_icon.png')?>",
            buttonImageOnly: true,
            buttonText: "Click to change date.",
            dateFormat: "mm/dd/y"
        });
    });
//]]>
</script>
