<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
// Get product and profile
$product = $this->getSubscription()->getProduct();
$platformProduct = $this->getSubscription()->getPlatformProduct();
?>

<div class="top-image">
	<?php // Product Image ?>
	<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(80); ?>" width="80" height="80" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" /></a>
</div>

<div class="top-name">
	<?php // Product Name ?>
	<?php $_productNameStripped = $this->stripTags($product->getName(), null, true); ?>
	<h2 class="product-name"><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $product->getName() ?></a></h2>

	<input type="text" id="product_id" name="product_id" value="<?php echo $product->getId() ?>"  class="input-text" style="display:none;" />
	<input type="text" id="product_profile_id" name="product_profile_id" value="<?php echo $platformProduct->getData('id') ?>"  class="input-text" style="display:none;" />

</div>
