<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2014 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
$subscription = $this->getSubscription();
$shippingAddress = $subscription->getShippingAddress();
?>

<div class="block-title">
	<h2>Shipping Address</h2>
</div>

<div class="box-padding">
	<p>Please select the address where your orders should be delivered: <a class="change" href="">(Change)</a></p>

	<address>
	<?php echo $shippingAddress->getFirstname() ?> <?php echo $shippingAddress->getLastname() ?><br/>
	<?php if(strlen($shippingAddress->getCompany())): ?>
	<?php echo $shippingAddress->getCompany() ?><br/>
	<?php endif; ?>
	<?php foreach($shippingAddress->getStreet() as $street): ?>
	<?php echo $street ?><br/>
	<?php endforeach; ?>
	<?php echo $shippingAddress->getCity() ?>, <?php echo $shippingAddress->getRegion() ?> <?php echo $shippingAddress->getPostcode() ?><br/>
	</address>

	<input type="text" id="shipping_address_id" name="shipping_address_id" value="<?php echo $shippingAddress->getId() ?>"  class="input-text" style="display:none;" />

	<div class="change">
		<div class="block-title">
			<h2>Change Shipping Address</h2>
		</div>
		<div class="block-content">
    		<?php echo $this->getChildHtml("shipping_address_select") ?>
		</div>
	</div>
</div>