<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<div class="page-title">
    <h1><?php echo $this->__("My Product Subscriptions") ?></h1>
</div>

<div id="mysubscriptions">
<?php
if($this->getNextOrderDateMode() != SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES
    && count($this->getActiveSubscriptions())):
?>
    <?php
    $activeSubscriptions = $this->getActiveSubscriptions();
    $firstSubscription = $activeSubscriptions[0];
    ?>
    <div class="subscription-more-details" id="all-subscriptions-details">
        <form id="all-subscriptions-date-form" class="all-subscriptions-date-form" action="<?php echo Mage::getUrl('autoship/mysubscriptions/change', array('_secure' => true)) ?>">
            <input type="hidden" name="id" id="subscription_id"
                   value="all_active"/>
            <p><?php echo $this->__("Next Ship Date:") ?></p>
            <div class="input-box">
                <input type="text" id="delivery_date"
                   name="delivery_date"
                   value="<?php echo $firstSubscription->getNextOrderDateText() ?>"
                   title="<?php echo $this->__('Next Ship Date:') ?>" class="input-text delivery_date"/>
            </div>
        </form>
        <?php
            echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription')
                ->setParentBlock($this)
                ->setTemplate('autoship/mysubscriptions/subscription/shipping_address.phtml')
                ->setSubscription($firstSubscription)
                ->toHtml();
            echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription')
                ->setParentBlock($this)
                ->setTemplate('autoship/mysubscriptions/subscription/billing_address.phtml')
                ->setSubscription($firstSubscription)
                ->toHtml();
            echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription')
                ->setParentBlock($this)
                ->setTemplate('autoship/mysubscriptions/subscription/payment.phtml')
                ->setSubscription($firstSubscription)
                ->toHtml();
        ?>
        <div class="clearer"></div>
    </div>
<?php endif; ?>

<div class="active-subscriptions">
	<?php foreach($this->getActiveSubscriptions() as $subscription): ?>
        <div class="subscription-block">
        <?php echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription')
            ->setTemplate('autoship/mysubscriptions/subscription.phtml')
            ->setSubscription($subscription)
            ->toHtml() ?>
        </div>
	<?php endforeach; ?>
</div>
</div>
<div class="inactive-subscriptions">
	<?php foreach($this->getInactiveSubscriptions() as $subscription): ?>
        <div class="subscription-block">
        <?php echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription')
            ->setTemplate('autoship/mysubscriptions/subscription.phtml')
            ->setSubscription($subscription)
            ->toHtml()
        ?>
        </div>
	<?php endforeach; ?>
</div>
<span class="please-wait" id="please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Updating...') ?>" title="<?php echo $this->__('Updating...') ?>" class="v-middle" /> <?php echo $this->__('Updating...') ?>
</span>
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo Mage::getUrl('customer/account/'); ?>"><small>&#171;</small> <?php echo $this->__("Back") ?></a></p>
</div>

<script type="text/javascript">
    //<![CDATA[
    var regionsJson =
        <?php echo $this->helper('directory')->getRegionJson() ?>
        ;
    <?php if ($this->getNextOrderDateMode() == SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES): ?>
    var editMultipleSubscriptions = false;
    <?php endif; ?>
    <?php if ($this->getNextOrderDateMode() != SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES): ?>
    $j(function () {
        $j("#delivery_date").datepicker({
            minDate: 2,
            showOn: "button",
            buttonImage: "<?php echo $this->getSkinUrl('images/autoship/calendar_icon.png')?>",
            buttonImageOnly: true,
            buttonText: "Click to change date.",
            dateFormat: "mm/dd/y",
            onSelect: function () {
                var form = $j(this).closest("form");
                updateAllSubscriptions(form);
            }
        });
    });
    var editMultipleSubscriptions = true;
    <?php endif; ?>
    //]]>
</script>
