<div class="compare-page-new-tabs">
    <div class="row">
        <ul class="tab-title">
            <?php
            $children = $this->getSortedChildBlocks();
            $i = 0;
            $last = count($children);
            ?>
            <?php foreach($children as $child):?>
                <li class="tab-selector <?php echo (!$i) ? 'tab-active' : '';?>" data-tab="<?php echo $i++?>"><?php echo $this->__($child->getLabel());?></li>
                <?php if ($i != $last):?>
                    <li class="tab-separator"></li>
                <?php endif;?>
            <?php endforeach ?>
        </ul>
        <div class="tab-content">
            <?php $i = 0; ?>
            <?php foreach($children as $child):?>
                <div class="tab-container" id="tab-container-<?php echo $i;?>" style="display:<?php echo (!$i++) ? 'block' : 'none';?>;">
                    <?php echo $child->toHtml();?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    addEvent(window, 'load', function() {
        jQuery('.tab-selector').mouseenter(function(){
            jQuery('.tab-selector.tab-active').removeClass('tab-active');
            jQuery(this).addClass('tab-active');
            jQuery('.tab-container').hide();
            jQuery('#tab-container-' + jQuery(this).data('tab')).show();
        })
    });
    //]]>
</script>