<?php

$links = array(
    array(
        'name' => 'account',
        'path' => 'customer/account/',
        'label' => 'Account Dashboard',
    ),
    array(
        'name' => 'account_edit',
        'path' => 'customer/account/edit/',
        'label' => 'Account Information',
    ),
    array(
        'name' => 'address_book',
        'path' => 'customer/address/',
        'label' => 'Address Book',
    ),
    array(
        'name' => 'orders',
        'path' => 'sales/order/history/',
        'label' => 'My Orders',
    ),
//    array(
//        'name' => 'my_subscriptions',
//        'path' => 'subscriptions/',
//        'label' => 'My Subscriptions',
//    )
    array(
        'name'  =>  'mysubscriptions',
        'path'  =>  'autoship/mysubscriptions',
        'label' =>  'My Product Subscriptions'
    ),

    array(
        'name'  =>  'creditcards',
        'path'  =>  'creditcards/',
        'label' =>  'My Credit Cards'
    ),


    array(
        'name'  =>  'logout',
        'path'  =>  'customer/account/logout/',
        'label' =>  'Sign Out'
    )

);


//////////-----START-----////////////
//  Description:  The following two options (Store Credit and Gift Card) need to be controlled via admin panel.
//  There is a fix for the following in layout.xml, but due to customization of "My Account" navigation links
//  the fix will not work and hence the condition.
//
//  @author     Ashutosh Potdar <apotdar@lyonscg.com>
//  @license    Lyons Consulting Group  <http://www.lyonscg.com>

if (Mage::getStoreConfig('customer/enterprise_customerbalance/is_enabled')) {
    $links[] = array(
        'name' => 'enterprise_customerbalance',
        'path' => 'enterprise_customerbalance/info/',
        'label' => 'Store Credit',
    );
}

if (Mage::getStoreConfig('enterprise_giftregistry/gift_card/enabled', Mage::app()->getStore()->getId())) {
    $links[] = array(
        'name' => 'enterprise_giftcardaccount',
        'path' => 'enterprise_giftcardaccount/customer/',
        'label' => 'Gift Card',
    );
}

//////////-----END-----////////////

$this->removeAllLink();

foreach($links as $link){
    $this->addLink($link['name'], $link['path'], $link['label']);
}
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
