<div class="filterfinder-popup active">
    <div class="filterfinder-popup-placeholder"></div>
    <div class="filterfinder-popup-inner">
        <div class="dfs-bootstrap">
            <?php echo $this->getLayout()->getBlock('root')->getChildHtml('messages'); ?>
            <div class="filterfinder-popup-header">
                <h3><span><?php echo $this->__('Refrigerator')?></span></h3>
                <span class="close"></span>
            </div>
            <div class="filterfinder popup">
    <!--            <div class="infoplate"><strong>--><?php //echo $this->__('Find Your Filter');?><!--</strong>--><?php //echo $this->__(' in a Flash:');?><!--</div>-->
    <!--            <ul class="infolist">-->
    <!--                <li><strong>--><?php //echo $this->__('Find Your Filter');?><!--</strong>--><?php //echo $this->__(' in a Flash:');?><!--</li>-->
    <!--                <li><strong>--><?php //echo $this->__('Find & Click');?><!--</strong>--><?php //echo $this->__(' Your Fridge Style:');?><!--</li>-->
    <!--                <li><strong>--><?php //echo $this->__('Find &; Click');?><!--</strong>--><?php //echo $this->__(' Your Filter Location:');?><!--</li>-->
    <!--                <li><strong>--><?php //echo $this->__('Find & Click');?><!--</strong>--><?php //echo $this->__(' Your Style of Filter Fit:');?><!--</li>-->
    <!--                <li><strong>--><?php //echo $this->__('Have Fun!');?><!--</strong></li>-->
    <!--            </ul>    -->
                <?php $stepsData = $this->allSteps; ?>
                <div class="ffcontent">
                    <?php $_filters = $this->getFilters(); $i = 0; ?>
                    <?php foreach ($stepsData as $_optionId => $item): $i++; ?>
                        <div class="step holder<?php echo $i; ?>
                        <?php echo ($i - 1 <= $this->currentStep) ? 'active ' : ''; ?><?php echo ($i - 1 == $this->currentStep) ? 'clicked ' : ''; ?>">
                            <div class="clicker step<?php echo $i; ?>">
                                <span class="info" title="<?php echo $this->__($_filters[$_optionId]->getFrontendLabel()); ?>">
                                        <?php
                                        if ($this->steps[$_optionId] !== NULL) {
                                            if (preg_match("/^\d+$/", $this->steps[$_optionId])) {
                                                echo $stepsData[$_optionId][$this->steps[$_optionId]]['label'];
                                            } else {
                                                echo $this->steps[$_optionId];
                                            }
                                        } else
                                            echo $this->__($_filters[$_optionId]->getFrontendLabel());
                                        ?>
                                    </span>
                            </div>
                            <div class="disable">&nbsp;</div>
                            <?php if ($item !== NULL): ?>
                                <ul class="options">
                                    <?php foreach ($item as $id => $value): ?>
                                        <?php if ($i == 1): ?>
                                            <li class="col-xs-12">
                                                <a class="steplink <?php echo (in_array($value['label'], $this->steps))? ' target' : ''; ?>"
                                                   href="<?php echo $this->getOptionUrl($value['label'], $_optionId); ?>">
                                                    <?php if ($value['imgUrl'] && strpos($value['imgUrl'], '<img') !== false): ?>
                                                        <?php if (strpos($value['imgUrl'], 'alt=""')): ?>
                                                            <?php $value['imgUrl'] = str_replace('alt=""', 'alt="' . $value['label'] . '"', $value['imgUrl']) ?>
                                                        <?php endif; ?>
                                                        <?php echo $value['imgUrl'] ?>
                                                        <span class="value-label"><?php echo $value['label'] ?></span>
                                                    <?php else: ?>
                                                        <img src="<?php echo $value['imgUrl']; ?>"
                                                             alt="<?php echo $value['label']; ?>"/>
                                                    <?php endif; ?>
                                                </a>
                                            </li>
                                        <?php else: ?>
                                            <li class="col-xs-6">
                                                <a class="steplink <?php echo (in_array($value['label'], $this->steps))? ' target' : ''; ?>"
                                                   href="<?php echo $this->getOptionUrl($value['label'], $_optionId); ?>">
                                                    <?php if ($value['imgUrl'] && strpos($value['imgUrl'], '<img') !== false): ?>
                                                        <?php if (strpos($value['imgUrl'], 'alt=""')): ?>
                                                            <?php $value['imgUrl'] = str_replace('alt=""', 'alt="' . $value['label'] . '"', $value['imgUrl']) ?>
                                                        <?php endif; ?>
                                                        <?php echo $value['imgUrl'] ?>
                                                    <?php else: ?>
                                                        <img src="<?php echo $value['imgUrl']; ?>"
                                                             alt="<?php echo $value['label']; ?>"/>
                                                    <?php endif; ?>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            <?php else: ?>
                                <div class="options">
                                    <img class="progressbar"
                                         src="<?php echo $this->getSkinUrl('images/loading_icon.gif') ?>"
                                         alt="progress bar"/>
                                </div>
                            <?php endif; ?>
                            <div class="clear">&nbsp;</div>
                        </div>
                    <?php endforeach; ?>

                    <?php if ($this->currentStep > 3): ?>
                        <div id="productList" class="visible">
                            <div class="category-products">
                                <?php $productList = $this->getLayout()->createBlock('lyonscg_filterfinder/product_list');
                                $productList->setProductCollection($this->prepareProductCollection());
                                $productList->setTemplate('filterfinder/list.phtml');
                                echo $productList->toHtml();
                                ?>
                            </div>
                        </div>
                    <?php else: ?>
                        <div id="productList">
                            <div class="category-products">
                                <div class="options">
                                    <img class="progressbar"
                                         src="<?php echo $this->getSkinUrl('images/loading_icon.gif') ?>"
                                         alt="progress bar"/>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    addEvent(window, 'load', function() {
        window.pageCount = 1;
        window.currentStep = <?php echo $this->currentStep; ?>;
        window.filterFinderBaseUrl = "<?php echo Mage::getBaseUrl(); ?>";
        /**
         * In dependensy of current step we show/not show default result heading
         */
        <?php if ($this->currentStep == 4){
            echo 'setProductsTitle();';
        }?>
        window.waitHtml = '<div class="options">' +
            '<img class="progressbar" src="<?php echo $this->getSkinUrl('images/loading_icon.gif') ?>" alt="progress bar"/>' +
            '</div>';
        window.waitProductHtml = '<div class="serch-result-title">Search Results</div><div class="category-products">' +
            '<div class="options"><img class="progressbar" ' +
            'src="<?php echo $this->getSkinUrl('images/loading_icon.gif') ?>" alt="progress bar"/></div></div>';
        window.waitCollection = '<div class="options"><img class="progressbar" ' +
            'src="<?php echo $this->getSkinUrl('images/loading_icon.gif') ?>" alt="progress bar"/></div></div>';

        setArrow();
        setInfo(window.currentStep);
        if(window.currentStep){
            setProductsTitle(window.currentStep-1);
        }
    });
</script>
