<?php $stepsData = $this->allSteps; ?>
<?php $filterFinderBrand = $this->allSteps['filter_finder_brand']; ?>
<?php if(!is_null($filterFinderBrand)): ?>
    <label class="finder-brand-label">
        <select class="finder-brand-select">
            <option value='0' disabled="disabled" selected><?php echo $this->__('select brand'); ?></option>
        <?php foreach ($filterFinderBrand as $id => $value): ?>
            <option value="<?php echo $value['label']; ?>"><?php echo $this->__($value['label']); ?></option>
        <?php endforeach; ?>
        </select>
    </label>
<?php endif; ?>
