<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
$subscription = $this->getSubscription();
$product = $this->getProduct();
?>
<div class="subscription-actions">
    <?php if ($subscription->getStatus() == 'Active'): ?>
        <?php if ($this->getNextOrderDateMode() == SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES): ?>
        <button type="button" title="<?php echo $this->__('Skip Next Delivery') ?>" class="button adjust skip">
            <span><span><?php echo $this->__('Skip Next Delivery') ?></span></span></button>
        <?php endif; ?>
        <div>
            <p><a href="<?php echo $this->getUrl('autoship/mysubscriptions/cancel/id/' . $subscription->getSubscriptionId(),
                    array('_secure' => true)) ?>" class="adjust cancel"><?php echo $this->__('Cancel Subscription') ?></a></p>

            <p><a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->__("Need more immediately?") ?></a></p>

            <p>&nbsp;</p>

            <?php if ($this->getNextOrderDateMode() == SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES): ?>
            <p><a href="<?php echo $subscription->getSubscriptionId() ?>-more-details-div"
                  class="link more details"><?php echo $this->__("More Details...") ?></a></p>
            <?php endif; ?>
        </div>
    <?php elseif ($subscription->getStatus() == 'Failed' || $subscription->getStatus() == 'Retry'): ?>
        <p>Status:</p>
        <p><span class="status"><strong><?php echo $subscription->getStatus() ?></strong></span></p>
        <div>
            <p><a href="<?php echo $this->getUrl('autoship/mysubscriptions/restart/id/' . $subscription->getSubscriptionId(),
                    array('_secure' => true)) ?>" class="adjust restart"><?php echo $this->__('Restart Subscription') ?></a></p>

            <p>&nbsp;</p>

            <?php if ($this->getNextOrderDateMode() == SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES): ?>
                <p><a href="<?php echo $subscription->getSubscriptionId() ?>-more-details-div"
                      class="link more details"><?php echo $this->__("More Details...") ?></a></p>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <p>Status:</p>
        <p><span class="status"><strong><?php echo $subscription->getStatus() ?></strong></span></p>
    <?php endif; ?>
</div>
<div class="adjust skip-delivery" style="display:none;">
    <div class="block-title">
        <h2><?php echo $this->__("Skip Delivery?") ?></h2>
    </div>
    <div class="block-content">
        <p>Skipping delivery on <?php echo $subscription->getNextOrderDateText() ?>.</p>

        <div class="buttons-set">
            <button type="button" title="<?php echo $this->__('Okay') ?>" href="<?php echo Mage::getUrl('autoship/mysubscriptions/skip',
                array(
                    'id' => $subscription->getSubscriptionId(),
                    '_secure' => true,
                )) ?>" class="button skip_yes"><span><span><?php echo $this->__('Okay') ?></span></span></button>
            <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button no">
                <span><span><?php echo $this->__('Cancel') ?></span></span></button>
        </div>
    </div>
</div>
<div class="adjust cancel" style="display:none;">
    <div class="block-title">
        <h2><?php echo $this->__("Cancel Subscription?") ?></h2>
    </div>
    <div class="block-content">
        <p><?php echo $this->__("Are you sure you want to cancel your subscription?") ?></p>

        <div class="buttons-set">
            <button type="button" title="<?php echo $this->__('Yes') ?>"
                    href="<?php echo Mage::getUrl('autoship/mysubscriptions/cancel', array(
                        'id' => $subscription->getSubscriptionId(),
                        '_secure' => true
                    )) ?>" class="button cancel_yes"><span><span><?php echo $this->__('Yes') ?></span></span></button>
            <button type="button" title="<?php echo $this->__('No') ?>" class="button no">
                <span><span><?php echo $this->__('No') ?></span></span></button>
        </div>
    </div>
</div>
<div class="adjust restart" style="display:none;">
    <div class="block-title">
        <h2><?php echo $this->__("Restart Subscription?") ?></h2>
    </div>
    <div class="block-content">
        <p><?php echo $this->__("Are you sure you want to restart your subscription?") ?></p>

        <div class="buttons-set">
            <button type="button" title="<?php echo $this->__('Yes') ?>"
                    href="<?php echo Mage::getUrl('autoship/mysubscriptions/restart', array(
                        'id' => $subscription->getSubscriptionId(),
                        '_secure' => true
                    )) ?>" class="button restart_yes"><span><span><?php echo $this->__('Yes') ?></span></span></button>
            <button type="button" title="<?php echo $this->__('No') ?>" class="button no">
                <span><span><?php echo $this->__('No') ?></span></span></button>
        </div>
    </div>
</div>

