<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
$subscription = $this->getSubscription();
$billingAddress = $subscription->getBillingAddress();
?>
<div class="block subscription-billing-address">
    <p><strong><?php echo $this->__("Billing address:") ?></strong> <a class="adjust" href=""><?php echo $this->__("(Change)") ?></a></p>
    <address>
        <?php echo $billingAddress->getFirstname() ?> <?php echo $billingAddress->getLastname() ?><br/>
        <?php if (strlen($billingAddress->getCompany())): ?>
            <?php echo $billingAddress->getCompany() ?><br/>
        <?php endif; ?>
        <?php foreach ($billingAddress->getStreet() as $street): ?>
            <?php echo $street ?><br/>
        <?php endforeach; ?>
        <?php echo $billingAddress->getCity() ?>
        , <?php echo $billingAddress->getRegion() ?> <?php echo $billingAddress->getPostcode() ?><br/>
    </address>

    <input type="text" id="billing_address_id" name="billing_address_id" value="<?php echo $billingAddress->getId() ?>"
           class="input-text" style="display:none;"/>

    <div class="adjust" style="display: none;">
        <div class="block-title">
            <h2><?php echo $this->__("Change Billing Address") ?></h2>
        </div>
        <div class="block-content">
            <?php
            // Output payment form
            echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription_form_billing')
                ->setParentBlock($this)
                ->setTemplate('autoship/subscription/form/billing.phtml')
                ->setSubscription($this->getSubscription())
                ->toHtml();
            ?>
        </div>
    </div>
</div>
