<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php
$subscription = $this->getSubscription();
$shippingAddress = $subscription->getShippingAddress();
?>
<div class="block subscription-shipping-address">
    <p><strong><?php echo $this->__("Delivery address:") ?></strong> <a class="adjust" href=""><?php echo $this->__("(Change)") ?></a></p>
    <address>
        <?php echo $shippingAddress->getFirstname() ?> <?php echo $shippingAddress->getLastname() ?><br/>
        <?php if (strlen($shippingAddress->getCompany())): ?>
            <?php echo $shippingAddress->getCompany() ?><br/>
        <?php endif; ?>
        <?php foreach ($shippingAddress->getStreet() as $street): ?>
            <?php echo $street ?><br/>
        <?php endforeach; ?>
        <?php echo $shippingAddress->getCity() ?>
        , <?php echo $shippingAddress->getRegion() ?> <?php echo $shippingAddress->getPostcode() ?><br/>
    </address>

    <input type="text" id="shipping_address_id" name="shipping_address_id" value="<?php echo $shippingAddress->getId() ?>"
           class="input-text" style="display:none;"/>

    <div class="adjust" style="display: none;">
        <div class="block-title">
            <h2><?php echo $this->__("Change Shipping Address") ?></h2>
        </div>
        <div class="block-content">
            <?php
            // Output payment form
            echo $this->getLayout()->createBlock('autoship/mysubscriptions_subscription_form_shipping')
                ->setParentBlock($this)
                ->setTemplate('autoship/subscription/form/shipping.phtml')
                ->setSubscription($this->getSubscription())
                ->toHtml();
            ?>
        </div>
    </div>
</div>
