<?php
	$ids = $this->getProductIds();
	$ids = explode(",", $ids);

	$modelProduct = Mage::getModel('catalog/product');
	$modelUrl	  = Mage::getModel('core/url');
	$_helper      = $this->helper('catalog/output');
	$store_id	  = Mage::app()->getStore()->getStoreId();
	$suffix 	  = Mage::helper('catalog/product')->getProductUrlSuffix($store_id);

    $_columnCount = 3; ?>
    <?php foreach ($ids as $id): ?>
        <?php $_product = $modelProduct->load($id); ?>
        <?php $package_qty = $_product->getPackageQty(); ?>
        <?php if (is_numeric($package_qty) && (int)$package_qty != 1) : ?>
            <?php $variant = $package_qty.'pk'; ?>
        <?php else : ?>
            <?php $variant = 'single'; ?>
        <?php endif; ?>
        <?php $brand = ($_product->getAttributeText('manufacturer') ? $this->jsQuoteEscape($_product->getAttributeText('manufacturer')) : null); ?>
        <?php $_noLongerSold = $_product->getNotForSale(); ?>
        <?php $buttonTitle = 'Add to Cart'; ?>
        <?php $productName = $this->jsQuoteEscape($_product->getName()) ?>
        <?php $productUrl = $modelUrl->getDirectUrl($modelProduct->formatUrlKey($_product->getUrlKey()).'.'.$suffix) ?>
        <?php $productCategory = null; ?>
        <?php if ($_product->getTypeId() == 'bundle') {
            $locationUrl = $this->getUrl('bundle/cart/add',
                array(
                    'id' => $_product->getId(),
                    Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED => Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl()),
                    Mage_Core_Model_Url::FORM_KEY => Mage::getSingleton('core/session')->getFormKey()
                )
            );
            $onClick = "onAddToCart('{$_product->getSku()}', '{$productName}', '{$_product->getFinalPrice()}', '1', '{$productCategory}', '{$variant}', '{$brand}' );";
        } elseif ($_product->getTypeId() == 'grouped') {
            $locationUrl = Mage::helper('checkout/cart')->getAddUrl($_product, array());
            $buttonTitle = 'View Details';
            $onClick = "onProductClick('{$_product->getSku()}', '{$productName}', 'Category', '{$productCategory}', '{$variant}', '{$brand}');";
        } else {
            $locationUrl = Mage::helper('checkout/cart')->getAddUrl($_product, array());
            $onClick = "onAddToCart('{$_product->getSku()}', '{$productName}', '{$_product->getFinalPrice()}', '1', '{$productCategory}', '{$variant}', '{$brand}' );";
        }?>
		<div class="col-lg-4 col-md-6">
			<div class="single-course">
				<div class="thumb">
					<a href="<?php echo $productUrl ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(198); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					</a>
				</div>
				<h4>
					<a href="<?php echo $productUrl ?>"
					   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"
					   onclick="onProductClick('<?php echo $_product->getSku() ?>',
							   '<?php echo $this->jsQuoteEscape($_product->getName()) ?>',
							   'Category',
							   '<?php echo $productCategory ?>' ,
							   '<?php echo $variant ?>',
							   '<?php echo $brand ?>' );">
						<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
					</a>
					<?php if($_product->getProductOptions()): ?>
						<div style="font-size: 12px"><?php echo $_product->getProductOptions(); ?></div>
					<?php endif; ?>
				</h4>
				<div class="course-box">
					<?php if (!$_noLongerSold): ?>
						<span><?php echo Mage::helper('core')->currency($_product->getPrice(), true, false) ?></span><br>
					<?php else:?>
						<div class="price-box"></div>
					<?php endif; ?>

					<?php if( $_product->getNotForSale() ): ?>
						<a title="<?php echo $this->__('View Details') ?>" class="course-status" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );setLocation('<?php echo $productUrl ?>')"><?php echo $this->__('View Details') ?></a>
					<?php elseif($_product->isSaleable()): ?>
						<a title="<?php echo $this->__($buttonTitle) ?>" class="course-status" onclick="<?php echo $onClick ?>setLocation('<?php echo $locationUrl ?>')"><?php echo $this->__($buttonTitle) ?></a>
					<?php else: ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif; ?>

					<ul class="add-to-links">
						<?php if($_compareUrl=Mage::helper('catalog/product_compare')->getAddUrl($_product)): ?>
								<input type="checkbox" name="compare_product_id[<?php echo $_product->getId() ?>]" value="<?php echo $_product->getId() ?>" />
								<a rel="nofollow" href="<?php echo $_compareUrl?>" class="product_compare_action" ><?php echo $this->__('Compare')  ?></a>
						<?php endif; ?>
					</ul>
				</div>
			</div>
		</div>
	<?php endforeach ?>