<!-- INCLUDE RESPONSIVE CSS & JS -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/grid.css')?>" media="screen" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/override.js')?>"></script>

<?php
	$this->setColumnCount(5);
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_helperUV = $this->helper('uswf_universalvariable');
// Enhanced Google Ecommerce Variables
    $currentPosition = 1;
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<section class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php $package_qty = $_product->getPackageQty(); ?>
        <?php if (is_numeric($package_qty) && (int)$package_qty != 1) : ?>
            <?php $variant = $package_qty.'pk'; ?>
        <?php else : ?>
            <?php $variant = 'single'; ?>
        <?php endif; ?>
        <?php $brand = ($_product->getAttributeText('manufacturer') ? $this->jsQuoteEscape($_product->getAttributeText('manufacturer')) : null); ?>
        <?php $productCategory = $_helperUV->getAttributeValue($_product->getId(), 'item_type'); ?>

        <?php $_noLongerSold = $_product->getNotForSale() ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>" data-product_url="<?php echo $_product->getProductUrl() ?>">
            <?php // Product Image ?>
            <div class="grid_3 alpha">
                <div class="product-img-box">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>' );"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(520, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div></a>
                    <?php // Fancybox
                    if (isset($fancybox) && $fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                        <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>' );">&nbsp;</a>
                    <?php endif; // End Fancybox ?>
                    <div class="img-shadow"><div><div></div></div></div>
                </div>
            </div>
            <?php // Product description ?>
            <div class="grid_6 omega content-border-product">
<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                <?php if (!$_noLongerSold): ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                <?php endif; ?>
                <?php $this->helper('yotpo')->showBottomline($this, $_product); ?>
                <?php if(!$_product->isSaleable()): ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                <div class="clear"></div>
                <div class="desc std">
                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );"><?php echo $this->__('Learn More') ?></a>
                </div>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" ><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a rel="nofollow" href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
                <?php if ($_product->isSaleable() && !$_noLongerSold): ?>
                    <p>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                onclick="onAddToCart('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', '<?php echo $_product->getFinalPrice() ?>', '1', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <span>
                                <span><?php echo $this->__('Add to Cart') ?></span>
                            </span>
                        </button>
                    </p>
                <?php elseif ($_noLongerSold): ?>
                    <p>
                        <button type="button" title="<?php echo $this->__('View Details'); ?>" class="button details"
                                onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );setLocation('<?php echo $_product->getProductUrl(); ?>')">
                            <span>
                                <span><?php echo $this->__('View Details'); ?></span>
                            </span>
                        </button>
                    </p>
                <?php endif; ?>
            </div>            
        </li>
        <script type="text/javascript">
            try {
                ga('ec:addImpression', {
                    'id'        :   '<?php echo $_product->getSku() ?>',
                    'name'      :   '<?php echo $this->jsQuoteEscape($_product->getName()) ?>',
                    'list'      :   'Category',
                    'category'  :   '<?php echo $productCategory ?>',
                    'brand'     :   '<?php echo $brand ?>',
                    'variant'   :   '<?php echo $variant ?>',
                    'position'  :   '<?php echo $currentPosition++ ?>'
                });
            } catch (e) {}
        </script>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">
        try {
            ga('send', 'event', 'catalog', 'impression', {'nonInteraction': true});
        } catch (e) {}
    </script>
    <script type="text/javascript">
        addEvent(window, 'load', function() {
            decorateList('products-list', 'none-recursive')
        });
    </script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    
    <ul class="products-grid">
    <?php $i=1; foreach ($_productCollection as $_product): ?>
        <?php $package_qty = $_product->getPackageQty(); ?>
        <?php if (is_numeric($package_qty) && (int)$package_qty != 1) : ?>
            <?php $variant = $package_qty.'pk'; ?>
        <?php else : ?>
            <?php $variant = 'single'; ?>
        <?php endif; ?>
        <?php $brand = ($_product->getAttributeText('manufacturer') ? $this->jsQuoteEscape($_product->getAttributeText('manufacturer')) : null); ?>
        <?php $productCategory = ($_product->getCategory() ? $this->jsQuoteEscape($_product->getCategory()->getName()) : null); ?>
        <?php $_noLongerSold = $_product->getNotForSale(); ?>
            <li class="grid_3 item <?php if(!($i%5) or ($i==1)): ?>alpha<?php endif; ?> <?php if(!($i%4)): ?>omega<?php endif; ?>" data-product_url="<?php echo $_product->getProductUrl() ?>">
                <div class="grid-indent">
                    <div class="product-box item-inner">
                        <div class="content-border-product">
							<div class="product-img-box">
                                <?php
                                $_imgAttr = 'small_image';
                                if (!trim($_product->getData($_imgAttr)) || $_product->getData($_imgAttr) == 'no_selection') {
                                    // need a product load since 'image' is not included in flat tables
                                    // should not be a big problem, since most products have small_image
                                    $_product->load($_product->getId());
                                    if ($_product->getData('image') && $_product->getData('image') != 'no_selection') {
                                        $_imgAttr = 'image';
                                    }
                                }
                                ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, $_imgAttr), null, true) ?>" class="product-image" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );">
                                    <?php
                                        $specialprice = $_product->getSpecialPrice();
                                        $specialPriceFromDate = $_product->getSpecialFromDate();
                                        $specialPriceToDate = $_product->getSpecialToDate();
                                        $today =  time();

                                        if ($specialprice)
                                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)):?>
                                                <div style="position:absolute;left:22px;top:5px;">
                                                    <img src="<?php echo $this->getSkinUrl('images/icon-sale.png') ?>">
                                                </div>
                                    <?php endif;?>
                                    <div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, $_imgAttr)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(420, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, $_imgAttr), null, true) ?>" />
                                    </div>
                                </a>
								<div class="img-shadow"><div><div></div></div></div>
							</div>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php $new_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <?php $_noLongerSold = $new_product->getNotForSale(); ?>
                            <?php if (!$_noLongerSold): ?>
                                <?php echo $this->getPriceHtml($new_product, true) ?>
                            <?php endif; ?>
                            <div class="yotpo-bottomline-container">
                                <?php $this->helper('yotpo')->showBottomline($this, $_product); ?>
                            </div>
							<div class="clear"></div>
                        </div>
                        <div class="actions">
                            <?php if($_product->isSaleable() && !$_noLongerSold): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                                        onclick="onAddToCart('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', '<?php echo $_product->getFinalPrice() ?>', '1', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                    <span>
                                        <span><?php echo $this->__('Add to Cart') ?></span>
                                    </span>
                                </button>
                            <?php elseif ($_noLongerSold): ?>
                                <button type="button" title="<?php echo $this->__('View Details'); ?>" class="button details"
                                        onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );setLocation('<?php echo $_product->getProductUrl(); ?>')">
                                    <span>
                                        <span><?php echo $this->__('View Details'); ?></span>
                                    </span>
                                </button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a rel="nofollow" href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
        <?php if ($category = $_product->getCategory()): ?>
            <?php $productCategory = $this->jsQuoteEscape($category->getName()) ?>
        <?php else: ?>
            <?php $productCategory = null ?>
        <?php endif; ?>
        <script type="text/javascript">
            try {
                ga('ec:addImpression', {
                    'id'        :   '<?php echo $_product->getSku() ?>',
                    'name'      :   '<?php echo $this->jsQuoteEscape($_product->getName()) ?>',
                    'list'      :   'Category',
                    'category'  :   '<?php echo $productCategory ?>',
                    'brand'     :   '<?php echo $brand ?>',
                    'variant'   :   '<?php echo $variant ?>',
                    'position'  :   '<?php echo $currentPosition++ ?>'
                });
            } catch (e) {}
        </script>
            <?php $i++; endforeach ?>
        </ul>
        <script type="text/javascript">
            try {
                ga('send', 'event', 'catalog', 'impression', {'nonInteraction': true});
            } catch (e) {}
        </script>
        <script type="text/javascript">
            addEvent(window, 'load', function() {
                decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])
            });
        </script>
        
    <?php endif; ?>
    
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</section>
<?php endif; ?>
<script>
    jQuery(document).on("click", '.yotpo-bottomline a', function(event) { 
        var ulr = jQuery(this).parents('li.item').data('product_url');
        if (typeof ulr != "undefined") {
            window.location.href = ulr+"#customer-reviews";
        }
    });
</script>
