<?php
$viewModel = $block->getData('view_model')
?>
<form class="form form-customerstatus" action="<?= $block->escapeUrl($viewModel->getFormUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Customer Status')) ?></span></legend><br>
        <div class="field">
            <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Customer Status')) ?></span></label>
            <div class="control">
                <input type="text" name="customer_status" id="customer-status" data-role="customer-status" value="<?= $viewModel->getCustomerStatus(); ?>" title="<?= $block->escapeHtmlAttr(__('Change Customer Status')) ?>" class="input-text" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>
</form>