
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_helperUV = $this->helper('uswf_universalvariable'); ?>
<?php $currentPosition = 1; ?>
<?php $_productCollection = $this->getItems(); ?>

<?php if($_collectionSize = count($_productCollection)): ?>
    <div class="titles">
        <h2><?php echo $this->__($this->getTitle()) ?></h2>
    </div>
<div class="crosssell-horizontal">
    <?php $i = 0; ?>
    <?php $_columnCount = 4; ?>
    <?php foreach ($_productCollection as $_product): ?>
        <?php $package_qty = $_product->getPackageQty(); ?>
        <?php if (is_numeric($package_qty) && (int)$package_qty != 1) : ?>
            <?php $variant = $package_qty.'pk'; ?>
        <?php else : ?>
            <?php $variant = 'single'; ?>
        <?php endif; ?>
        <?php $brand = ($_product->getAttributeText('manufacturer') ? $this->jsQuoteEscape($_product->getAttributeText('manufacturer')) : null); ?>
        <?php $_noLongerSold = $_product->getNotForSale(); ?>
        <?php $buttonTitle = 'Add to Cart'; ?>
        <?php $productName = $this->jsQuoteEscape($_product->getName()) ?>
        <?php $productCategory = ($_product->getCategory() ? $this->jsQuoteEscape($_product->getCategory()->getName()) : null); ?>
        <?php if ($_product->getTypeId() == 'bundle') {
            $locationUrl = $this->getUrl('bundle/cart/add') . 'id' . DS . $_product->getId();
            $onClick = "onAddToCart('{$_product->getSku()}', '{$productName}', '{$_product->getFinalPrice()}', '1', '{$productCategory}', '{$variant}', '{$brand}' );";
        } elseif ($_product->getTypeId() == 'grouped') {
            $locationUrl = $_product->getProductUrl();
            $buttonTitle = 'View Details';
            $onClick = "onProductClick('{$_product->getSku()}', '{$productName}', 'Preview Cart', '{$productCategory}', '{$variant}', '{$brand}');";
        } else {
            $locationUrl = $this->getAddToCartUrl($_product);
            $onClick = "onAddToCart('{$_product->getSku()}', '{$productName}', '{$_product->getFinalPrice()}', '1', '{$productCategory}', '{$variant}', '{$brand}' );";
        }?>
        <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid">
        <?php endif ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" data-product_url="<?php echo $_product->getProductUrl() ?>">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(198); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <div class="product-shop">
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    <?php if($_product->getProductOptions()): ?>
                        <div style="font-size: 12px"><?php echo $_product->getProductOptions(); ?></div>
                    <?php endif; ?>
                </h2>
                <?php $this->helper('uswf_yotpo')->showBottomline($this, $_product); ?>
                <div class="price-box">
                    <?php if (!$_noLongerSold): ?>
                        <?php echo $this->getCustomPriceHtml($_product) ?>
                    <?php endif; ?>
                </div>
                <div class="actions">
                    <?php if( $_product->getNotForSale() ): ?>
                        <button type="button" title="<?php echo $this->__('View Details') ?>" class="button btn-cart" onclick="onProductClick('<?php echo $_product->getSku() ?>', '<?php echo $this->jsQuoteEscape($_product->getName()) ?>', 'Category', '<?php echo $productCategory ?>' , '<?php echo $variant ?>', '<?php echo $brand ?>' );setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>
                    <?php elseif($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__($buttonTitle) ?>" class="button btn-cart" onclick="<?php echo $onClick ?>setLocation('<?php echo $locationUrl ?>')"><span><span><?php echo $this->__($buttonTitle) ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </div>
        </li>
        <script type="text/javascript">
            try {
                ga('ec:addImpression', {
                    'id'        :   '<?php echo $_product->getSku() ?>',
                    'name'      :   '<?php echo $this->jsQuoteEscape($_product->getName()) ?>',
                    'list'      :   'Preview Cart',
                    'category'  :   '<?php echo $productCategory ?>',
                    'brand'     :   '<?php echo $brand ?>',
                    'variant'   :   '<?php echo $variant ?>',
                    'position'  :   '<?php echo $currentPosition++ ?>'
                });
            } catch (e) {}
        </script>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
        <?php endif ?>
    <?php endforeach; ?>

    <script type="text/javascript">
        try {
            ga('send', 'event', 'catalog', 'impression', {'nonInteraction': true});
        } catch (e) {}
    </script>
</div>

<?php endif; ?>
