<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php $_code = $this->getMethodCode() ?>
<?php $_billingAddress = $this->getBillingAddress() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" id="<?php echo $_code ?>_payment_token" name="payment[payment_token]" title="<?php echo $this->__('Payment Token') ?>" value="<?php echo $this->getAdditionalInfo('payment_token') ?>" />
    <input type="hidden" id="<?php echo $_code ?>_is_new_card" name="payment[is_new_card]" title="<?php echo $this->__('Is New Card') ?>" value="1" />
    <input type="hidden" id="<?php echo $_code ?>_firstname" name="payment[firstname]" title="<?php echo $this->__('firstname') ?>" value="<?php echo $_billingAddress->getData('firstname') ?>" />
    <input type="hidden" id="<?php echo $_code ?>_lastname" name="payment[lastname]" title="<?php echo $this->__('lastname') ?>" value="<?php echo $_billingAddress->getData('lastname') ?>" />
    <?php if($this->forceSaveCard()): ?>
    <input type="hidden" id="<?php echo $_code ?>_save_card" name="payment[save_card]" title="<?php echo $this->__('Save Card') ?>" value="1" />
    <?php endif; ?>
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="<?php echo $this->getAdditionalInfo('obscured_cc_number') ?>" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
        <li id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>"
                           class="input-text cvv required-entry validate-cc-cvn"
                           id="<?php echo $_code ?>_cc_cid"
                           name="payment[cc_cid]" value="<?php if(strlen($this->getAdditionalInfo('payment_token')) > 0): ?>XXX<?php endif; ?>" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
    <?php endif; ?>
    <?php if($this->useSaveCardCheckbox()): ?>
        <li id="<?php echo $_code ?>_cc_save_card_div">
            <label for="<?php echo $_code ?>_save_card" class="required"><em>*</em><?php echo $this->__('Save My Card') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type='hidden' value='0' name='payment[save_card]'/>
                    <input type="checkbox" title="<?php echo $this->__('Save Card') ?>" class="checkbox"
                           id="<?php echo $_code ?>_save_card" name="payment[save_card]"
                           value="1" <?php if($this->getAdditionalInfo('save_card')): ?>checked<?php endif; ?> />
                </div>
            </div>
        </li>
    <?php endif; ?>
</ul>
