<?php
/**
 * Sub Category Template File
 *
 * @category   Lyons
 * @package    Lyonscg_Widget
 * @copyright  Copyright (c) 2013 Lyons Consulting Group (www.lyonscg.com)
 * @author     Mark Hodge (mhodge@lyonscg.com)
 */
?>
<?php
/**
 * Sub Category template
 *
 * @see Lyonscg_Widget_Block_Category
 */
?>
<div class="category-container">
    <div class="category-list">
        <?php echo $this->getCatListing(); ?>
        <div class="clear"></div>
    </div>
</div>