<div class="content-header">
	<table cellspacing="0" class="grid-header">
	<tr>
		<td><h3><?php echo $this->__('My form title')?></h3></td>
	</tr>
	</table>
</div>
<div class="entry-edit">
	<form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post')?>">
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('This fieldset name')?></h4>
		<fieldset id="my-fieldset">
			<?php echo $this->__('Notice text')?>
			<br><br>
			<input id="validation" type="checkbox" name="validation" value="1">&nbsp;<label for="validation"><?php echo $this->__('Validation checkbox')?></label>
			<br><br>
			<button onclick="editForm.submit()" class="scalable save" type="button"><span>Execute Multi-Server Cache Clear</span></button>
		</fieldset>
	</form>
</div>
<script type="text/javascript">
	var editForm = new varienForm('edit_form');
</script>
