<div class="compared-to-top-hor-banner"><?php echo Mage::helper('uswf_comparedto')->getTopHorBannerImg()?></div>
<?php
    $_helper = $this->helper('catalog/output');
    $_helperUV = $this->helper('uswf_universalvariable');
?>
<?php if ($this->getProducts()): ?>
    <div class="compare-page container_24 compare-page-new">
        <div class="compare-wrapper">
            <div class="compare-products">
                <?php foreach ($this->getProducts() as $index => $product): ?>
                    <?php
                        $isTier1 = $product->getData('is_tier1');
                        $product->setIndex($index);
                    ?>
                    <?php $package_qty = $product->getPackageQty(); ?>
                    <?php if (is_numeric($package_qty) && (int)$package_qty != 1) : ?>
                        <?php $variant = $package_qty.'pk'; ?>
                    <?php else : ?>
                        <?php $variant = 'single'; ?>
                    <?php endif; ?>
                    <?php $brand = ($product->getAttributeText('manufacturer') ? $this->jsQuoteEscape($product->getAttributeText('manufacturer')) : null); ?>
                    <?php $productCategory = $_helperUV->getAttributeValue($product->getId(), 'item_type'); ?>
                    <?php $idForm = "product_addtocart_form$index "; ?>
                    <form action="<?php echo Mage::getUrl('groupedproductconfiguration/cart/add') ?>" method="post" id="product_addtocart_form<?php echo $index ?>" name="product_form<?php echo $index ?>"<?php if($product->getExtAssociatedProducts()): ?> enctype="multipart/form-data"<?php endif; ?> data-product_url="<?php echo $product->getProductUrl() ?>">
                        <div class="ind-item grid_12 product-compare-box-container<?php echo ($isTier1 ? ' alpha first ' : ' last ') . 'product-index-' . $index ?>">
                            <?php $ribbonImage = $isTier1 ? Mage::helper('uswf_comparedto')->getTier1RibbonImg($this, $index) : Mage::helper('uswf_comparedto')->getOemRibbonImg($this, $index);?>
                            <div class="ribbon-<?php echo $index;?>"><?php echo $ribbonImage ?></div>
                            <div class="border">
                                <div class="<?php echo $isTier1 ? 'low-cost-header' : 'current-selection-header' ?> a-center compared-to-pad-header">
                                    <?php if ($isTier1): ?>
                                        <img class="compare-to-title-choise" src="<?php echo $this->getSkinUrl('images/compareto/choise.png');?>">
                                    <?php endif;?>
                                    <?php echo $this->__($product->getExtLabel()); ?>
                                </div>
                                <div class="item first">
                                    <div class="left">
                                        <div class="product-image">
                                            <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>" class="product-image" onclick="onProductClick('<?php echo $product->getSku() ?>', '<?php echo $this->jsQuoteEscape($product->getName()) ?>', 'Compare', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');"><img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(175); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>" /></a>
                                        </div>
                                        <div class="clear"></div>
                                        <?php echo $this->getDummyReviewHtml($product); ?>
                                    </div>
                                    <div class="right">
                                        <div class="product-name">
                                            <h1 <?php echo Mage::helper('uswf_comparedto')->getProductDescStyle($this)?>><a href="<?php echo $product->getProductUrl()?>" onclick="onProductClick('<?php echo $product->getSku() ?>', '<?php echo $this->jsQuoteEscape($product->getName()) ?>', 'Category', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');"><?php echo $_helper->productAttribute($product, $product->getName() , 'name'); ?></a></h1>
                                            <?php if($product->getProductOptions()): ?>
                                                <div style="font-size: 12px"><?php echo $product->getProductOptions(); ?></div>
                                            <?php endif; ?>
                                            <?php if ($product->isSaleable()): ?>
                                                <div class="filter-in-stock"><?php echo $this->__('In Stock') ?></div>
                                            <?php else: ?>
                                                <div class="filter-out-of-stock"><?php echo $this->__('Out Of Stock') ?></div>
                                            <?php endif; ?>
                                            <span class="sku">
                                                <?php if ($this->getData('display_sku')):?>
                                                    <?php echo $this->__('Our#') ?> <?php echo $this->getOptionText($product, 'brand_actual', $product->getBrandActual()) . '-' . $product->getManufacturerId() ?>
                                                <?php endif;?>
                                            </span>
                                        </div>
                                        <?php if($product->isSaleable()): ?>
                                        <?php echo $this->getProductHtml($product); ?>
                                            <div class="addtocart">
                                                <button type="button" title="<?php echo $this->__($isTier1 ? 'Add to Cart & Save!' : 'Add to Cart') ?>" class="button btn-cart" onclick="onAddToCart('<?php echo $product->getSku() ?>', '<?php echo addslashes($_helper->productAttribute($product, $product->getName() , 'name')) ?>', jQuery('<?php echo '#'.$idForm ?>.css-checkbox:checked').parents('tr').find('.price-simple').text(), '1', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');product_addtocart_form<?php echo $index ?>.submit(this)">
                                                    <span class="<?php echo $isTier1 ? 'green' : 'blue' ?>"><span>
                                                        <div class="btn-main-row"><?php echo $this->__('Add to Cart');?></div>
                                                        <div class="btn-arrow-right"></div>
                                                        <?php if ($isTier1):?>
                                                            <div class="btn-secondary-row"><?php echo $this->__('AND SAVE!');?></div>
                                                        <?php endif;?>
                                                    </span></span>
                                                </button>
                                            </div>
                                        <?php endif;?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php if ($this->getDataHelper()->isRegisteredFrontend()): ?>
                            <?php if (Mage::registry('product') !== null): ?>
                                <?php Mage::unregister('product') ?>
                            <?php endif; ?>
                            <?php Mage::register('product', $product) ?>
                            <?php if ($product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_GROUPED): ?>
                                <script type="text/javascript">itorisGroupedOptions = []; opConfig = {reloadPrice : function(){}}; spConfig = {reloadPrice : function(){}}; bundle = {reloadPrice : function(){}};</script>
                                <link rel="stylesheet" type="text/css" href="<?php echo Mage::getDesign()->getSkinUrl('itoris/groupedproductconfiguration/css/groupedproduct.css', array()) ?>"/>
                                <div id="itoris_grouped_product_configuration">
                                    <?php $subProducts = $product->getTypeInstance(true)->getAssociatedProducts($product);?>
                                    <?php $img = array(); ?>
                                    <?php $productUrl = array(); ?>
                                    <?php foreach($subProducts as $subProduct): ?>
                                        <?php if ($subProduct->getHasOptions()): ?>
                                            <script type="text/javascript">
                                                addEvent(window, 'load', function() {
                                                    window.optionsPrice<?php echo $subProduct->getId();?> = new Product.OptionsPrice(<?php echo $this->getConfig($subProduct); ?>);
                                                });
                                            </script>
                                            <?php if (!$this->getAirfilters()):?>
                                                <div class="itoris_grouped_product_associated_product <?php if ($subProduct->getTypeId()=='bundle') {echo 'itoris_grouped_product_bundle';}?>" id="itoris_grouped_product_<?php echo $subProduct->getId();?>" style="display: none;">
                                                    <?php echo $this->optionBlock($subProduct)->toHtml();?>
                                                </div>
                                            <?php endif;?>
                                        <?php endif; ?>
                                        <?php
                                            if ($this->getDataHelper()->getSettings()->getShowImage()) {
                                                $img[$subProduct->getId()] = (string)Mage::helper('catalog/image')->init($subProduct, 'small_image')->resize(75);
                                            }
                                        ?>
                                        <?php
                                            if ($this->getDataHelper()->getSettings()->getMakeClickable()) {
                                                $productUrl[$subProduct->getId()] = $subProduct->getProductUrl();
                                            }
                                        ?>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif?>
                        <?php endif?>
                    </form>
                <?php endforeach; ?>
             </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('compare-page-tabs');?>
<?php endif; ?>

<script type="text/javascript">//<![CDATA[
    jQuery(window).bind('load resize',function(){
        jQuery('.ind-item').css('height','');
        if(jQuery(window).width() >= 960) {
            //pad height
            var firstProductHeight = jQuery('.ind-item.first').height();
            var secondProductHeight = jQuery('.ind-item.last').height();
            if (firstProductHeight > secondProductHeight) {
                jQuery('.ind-item.last').height(jQuery('.ind-item.first').height());
            } else {
                jQuery('.ind-item.first').height(jQuery('.ind-item.last').height());
            }
        }
    });
    addEvent(window, 'load', function() {
        //ribbon position
        jQuery('body .wrapper').css({'overflow': 'visible'});

        <?php for ($i = 1; $i <= 2; $i++): ?>
        <?php $productFormName = 'product_addtocart_form' . $i ?>
        <?php echo $productFormName ?> =
            new VarienForm('<?php echo $productFormName ?>');
        <?php echo $productFormName ?>.
        submit = function (button, url) {
            var canSubmit = false;
            var options = document.product_form<?php echo $i ?>.getElementsByClassName('option-validate');
            if (options.length == 0) {
                canSubmit = true;
            } else {
                for (var i = 0; i < options.length; i++) {
                    if (options[i].checked === true) {
                        canSubmit = true;
                    }
                }
            }
            if (canSubmit) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                    form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }
                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            } else {
                alert('Please specify the quantity of product(s).');
            }
        }.bind(<?php echo $productFormName ?>);

        <?php echo $productFormName ?>checkSelection = function (input) {
            $$('input[type=radio]:checked').each(function (element) {
                if (element.name != input.name) {
                    element.checked = false;
                }
            });
        }.bind(<?php echo $productFormName ?>);

        <?php echo $productFormName ?>.
        submitLight = function (button, url) {
            if (this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(<?php echo $productFormName ?>);
        <?php endfor; ?>
    });
    jQuery(document).on("click", '.yotpo-bottomline a', function(event) { 
        var ulr = jQuery(this).parents('.compare-products form').data('product_url');
        if (typeof ulr != "undefined") {
            window.location.href = ulr+"#customer-reviews";
        }
    });
//]]></script>
