<?php
    if (Mage::helper('uswf_smartfit')->isFeaturedEnabled()):
        $_helper = $this->helper('catalog/output');
?>
    <?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="page-title category-title">
        <h1><?php echo $this->__('New Products') ?></h1>
    </div>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid row">
            <?php endif ?>
                <li class="item col-md-3 col-sm-6<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" itemscope itemtype="http://schema.org/product">
                    <div class="item-wrapper">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/></a>
                        <div class="product-shop">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" itemprop="name"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                            <div class="actions">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <button type="button" title="<?php echo $this->__('Where to Buy') ?>" class="button btn-cart where-to-buy" onclick="setLocation('<?php echo $this->getUrl('storelocator'); ?>')"><span><span><?php echo $this->__('Where to Buy') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
            </ul>
            <?php endif ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif;?>