<?php 
if (Mage::getStoreConfig('newsletterpopup/general/active', Mage::app()->getStore())):?>
	
	<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newsletterpopup" aria-hidden="true" id="newsletterpopup2">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header block-title">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<strong><span><?php echo $this->__('Subscribe to our newsletter') ?></span></strong>
				</div>
				<div class="modal-body">
					<strong><span><?php echo $this->__('Subscribe to the masquerade masks mailing list to receive updates on new arrivals, special offers and other discount information.') ?></span></strong>
					<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
						<div class="block-content">
							<div class="form-group">
								<input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" placeholder="<?php echo $this->__('Enter your e-mail:') ?>" class="input-text required-entry validate-email" />
							</div>
							<div class="actions">
								<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button" name="newsletter_submit"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<?php 
	//var_dump(Mage::getSingleton('core/session'));

	// Script init for home page only
	if(Mage::getSingleton('cms/page')->getIdentifier() == 'home' && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') : ?>
		<script type="text/javascript">
			//<![CDATA[
				var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
			//]]>			
		</script>		

		<?php 
		// Popup init conditions
		if (Mage::getSingleton('core/session')->getSignedUpForNewsletter() == false) { ?>
			<script>
				jQuery(document).ready(function() {
					var newsPopup 		= jQuery('#newsletterpopup2');
					var newsPopupClose 	= newsPopup.find('.close');
					var showNewsPopup 	= localStorage.getItem("showNewsPopup");

					if (showNewsPopup != '0') {
						newsPopup.modal();
					};					

					newsPopupClose.click(function(){
						localStorage.setItem("showNewsPopup", '0');
					});

					console.log(showNewsPopup);
					console.log(typeof(showNewsPopup));
				});
			</script>
		<?php } ?>
	<?php endif; ?>
<?php endif; ?>