<?php
/* @var $this QuBit_UniversalVariable_Block_Uv */
$qubit_opentag_container_id               = Mage::getStoreConfig('qubit/qubit_opentag_container_id');
$qubit_opentag_async                      = Mage::getStoreConfig('qubit/qubit_opentag_async');
$qubit_opentag_enabled                    = Mage::getStoreConfig('qubit/qubit_opentag_enabled');
$qubit_universal_variable_enabled         = Mage::getStoreConfig('qubit/qubit_universal_variable_enabled');

$observer = 'universal_variable_main/page_observer';
$mage = Mage::getSingleton($observer);

//FORCE NO ASYNC
$qubit_opentag_async = '';
?>

<?php if ($qubit_universal_variable_enabled == 1) :?>
    <?php
    // extract variable only when universal variable is enabled
    $version         = $mage->getVersion();
    $page            = $mage->getPage();
    $product         = $mage->getProduct();
    $listing         = $mage->getListing();
    $magento_version = $mage->getMageVersion();
    $recommendation  = $mage->getRecommendation();
	$offer_id		 = $this->getOfferId();
	$affiliate_id	 = $this->getAffiliateId();
	$transaction_id	 = $this->getTransactionId();
    ?>
    <!-- Universal Variable Start -->
    <script type="text/javascript">
        window.universal_variable = window.universal_variable || {};
        window.universal_variable.version         = <?php echo json_encode($version); ?>;
        window.universal_variable.magento_version = <?php echo json_encode($magento_version) ?>;
        window.universal_variable.page            = <?php echo json_encode($page); ?>;
        <?php if ($product): ?>
        window.universal_variable.product         = <?php echo json_encode($product) ?>;
        <?php endif;?>
        <?php if ($listing): ?>
        window.universal_variable.listing         = <?php echo json_encode($listing) ?>;
        <?php endif;?>
        <?php if ($recommendation): ?>
        window.universal_variable.recommendation  = <?php echo json_encode($recommendation); ?>;
        <?php endif;?>
		window.universal_variable.offer_id		  = <?php echo json_encode($offer_id); ?>;
		window.universal_variable.affiliate_id	  = <?php echo json_encode($affiliate_id); ?>;
		window.universal_variable.transaction_id  = <?php echo json_encode($transaction_id); ?>;
    </script>
    <!-- Universal Variable End -->
    <!--SpringSearch listing processing start-->
    <script type="text/javascript">
        (function() {
            if (typeof window.universal_variable.listing != 'undefined') {
                var sortDirPattern = /(\?|\&)sort\.([^=]+)=([^\&\?]+)/i;
                var listingModePattern = /(\?|\&)resultLayout=([^\&\?]+)/i;
                if (typeof window.universal_variable.listing.sort_by == 'undefined') {
                    window.universal_variable.listing.sort_by = '<?php echo USWF_UniversalVariable_Model_Page_Observer::SEARCH_SPRING_DIRORDER_PARAMS_DEFAULT;?>';
                    if (window.location.hash) {
                        var matches = sortDirPattern.exec(window.location.hash);
                        if (matches && typeof matches == 'object' && (2 in matches) && (3 in matches)) {
                            window.universal_variable.listing.sort_by = matches[2] + '_' + matches[3];
                        }
                    }
                }
                if (typeof window.universal_variable.listing.layout == 'undefined') {
                    window.universal_variable.listing.layout = '<?php echo USWF_UniversalVariable_Model_Page_Observer::SEARCH_SPRING_LISTING_MODE_DEFAULT;?>';
                    if (window.location.hash) {
                        var matches = listingModePattern.exec(window.location.hash);
                        if (matches && typeof matches == 'object' && (2 in matches)) {
                            window.universal_variable.listing.layout = matches[2];
                        }
                    }
                }
            }
        }) ();
    </script>
    <!--SpringSearch listing processing end-->
    <!-- Add UV listeners for breadcrumbs, listing, basket start-->
    <script>
        window.uv_listener = window.uv_listener || [];
        window.uv_listener.push(["on", "change:page.breadcrumb", function() {
            window._qtd = window._qtd || [];
            window._qtd.push({ resendUniversalVariables: 1 });
        }]);
        window.uv_listener.push(["on", "change:listing", function() {
            window._qtd = window._qtd || [];
            window._qtd.push({ resendUniversalVariables: 1 });
        }]);
        window.uv_listener.push(["on", "change:basket", function() {
            window._qtd = window._qtd || [];
            window._qtd.push({ resendUniversalVariables: 1 });
        }]);
    </script>
    <!-- Add UV listeners for breadcrumbs and listing end-->
<?php endif;?>

<?php if ($qubit_opentag_container_id && $qubit_opentag_enabled == 1) :?>
    <!-- QuBit OpenTag Start -->
    <script type="text/javascript" src='//d3c3cq33003psk.cloudfront.net/opentag-<?php echo $qubit_opentag_container_id;?>.js' <?php echo $qubit_opentag_async;?>></script>
    <!-- QuBit OpenTag End -->

<?php endif;?>
