<?php
    $qubit_universal_variable_enabled         = Mage::getStoreConfig('qubit/qubit_universal_variable_enabled');
    $observer = 'universal_variable_main/page_observer';
    $mage = Mage::getSingleton($observer);
    $user = $mage->getUser();

    $basket          = $mage->getBasket();
    $transaction     = $mage->getTransaction();
    $events          = $mage->getEvents();
?>

<?php if (($qubit_universal_variable_enabled == 1) && $user): ?>
    <!-- Universal Variable Start -->
    <script type="text/javascript">
        window.universal_variable = window.universal_variable || {};
        window.universal_variable.user            = <?php echo json_encode($user); ?>;
        <?php if ($basket): ?>
        window.universal_variable.basket          = <?php echo json_encode($basket) ?>;
	<?php endif; ?>
        <?php if ($transaction): ?>
        window.universal_variable.transaction     = <?php echo json_encode($transaction) ?>;
        <?php endif;?> 
        window.universal_variable.events          = <?php echo json_encode($events); ?>;
        
    </script>
    <!-- Universal Variable End -->
<?php endif;?>
