<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products">
        <div class="page-title category-title">
            <h1><?php echo $this->__('Specials products') ?></h1>
        </div>
            <?php $suffix = $this->getNameInLayout(); ?>
            <ul class="products-grid row" id="widget-catalogsale-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item col-xs-12 col-sm-3" itemscope itemtype="http://schema.org/product">
                    <div class="item-wrapper">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>"  alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                        </a>
                        <div class="product-shop">
                                <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)" itemprop="name"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        
                            <div class="actions">
                                <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                          <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="label-product">             
                                <?php if($_product->getData('new')){echo '<span class="new">'.$this->__('New').'</span>';  }?>
                                <?php if($_product->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
                            </div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
</div>
<?php endif; ?>
