<?php
/**
 * Enter description here ...
 *
 * @category   Lyons
 * @package    ${MODULENAME}
 * @copyright  Copyright (c) 2013 Lyons Consulting Group (www.lyonscg.com)
 * @author     Mark Hodge (mhodge@lyonscg.com)
 */
?>
<?php $_helperUV = $this->helper('uswf_universalvariable'); ?>
<?php if(count($this->getItemCollection()->getItems())): ?>
    <div class="box-replaced">
        <div class="box">
            <p class="red"><?php echo $this->__('Recommended Replacement Product(s)') ?></p>
            <p><?php echo $this->getProduct()->getNotForSaleDescr() ?></p>
            <ul class="products-replaced">
                <?php $this->resetItemsIterator() ?>
                <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                    <?php $position = 'left' ?>
                    <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                        <?php if($_link=$this->getIterableItem()): ?>
                            <?php $package_qty = $_link->getPackageQty(); ?>
                            <?php if (is_numeric($package_qty) && (int)$package_qty != 1) : ?>
                                <?php $variant = $package_qty.'pk'; ?>
                            <?php else : ?>
                                <?php $variant = 'single'; ?>
                            <?php endif; ?>
                            <?php $brand = $_link->getAttributeText('manufacturer'); ?>
                            <?php $productCategory = $_helperUV->getAttributeValue($_link->getId(), 'item_type'); ?>
                            <li class="item <?php echo $position ?>">
                                <div class="product-box">
                                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" class="product-image" onclick="onProductClick('<?php echo $_link->getSku() ?>', '<?php echo $this->jsQuoteEscape($_link->getName()) ?>', 'Replacement products', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(130) ?>" width="130" height="130" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" /></a>
                                    <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" onclick="onProductClick('<?php echo $_link->getSku() ?>', '<?php echo $this->jsQuoteEscape($_link->getName()) ?>', 'Replacement products', '<?php echo $productCategory ?>', '<?php echo $variant ?>', '<?php echo $brand ?>');"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>

                                    <div class="yotpo-bottomLine-wrapper">
                                        <span class="hidden yotpo-data" data-url="<?php echo $_link->getProductUrl() ?>"></span>
                                        <?php $this->helper('uswf_yotpo')->showBottomline($this, $_link); ?>
                                    </div>
                                    <?php echo $this->getPriceHtml($_link, true, '-replaced') ?>
                                </div>
                            </li>
                            <?php if ($position == 'left'): ?>
                                <?php $position = 'right' ?>
                            <?php elseif ($position == 'right'): ?>
                                <div class="clear"></div>
                                <?php $position = 'left' ?>
                            <?php endif; ?>
                        <?php else: ?>
                        <?php endif; ?>
                    <?php endfor; ?>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
<?php endif ?>
