<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_helperLinksCatalog = $this->helper('uswf_linkscatalog'); ?>
<?php $product = Mage::registry('current_product'); ?>
<?php $_product = Mage::getModel('catalog/product')->load($product->getId());//$this->getProduct(); ?>

<?php if ($_product->getHasContaminants()): ?>
    <div class="box-collateral box-contaminants">
        <h2><?php echo $this->__('Contaminants') ?></h2>
        <div class="box-collateral-content">
            <div class="std"><?php echo $_product->getAttributeText('contaminants_header') ?>
                <?php $attributesCollection = Mage::getResourceModel('catalog/product_attribute_collection') ?>
                <?php $attributesCollection->setAttributeGroupFilter(23) ?>
                <ul class="contaminants-attributes">
                    <?php foreach ($attributesCollection as $attribute): ?>
                        <?php $_attributeCode = $attribute->getAttributeCode() ?>
                        <?php $valAtrr = $_product->getResource()->getAttribute($_attributeCode)->getFrontend()->getValue($_product) ?>
                        <?php if ($_attributeCode == 'fluoride' && $valAtrr == 'NF'): ?>
                            <?php $attrUrl = $_helperLinksCatalog->getAttrContaminantsUrl($_attributeCode); ?>
                            <?php if (!empty($attrUrl)): ?>
                                <?php $attrUrl = Mage::getBaseUrl().$attrUrl; ?>
                                <?php $urlContaminants =  "<a class=\"title\" href=\"{$attrUrl}\">fluoride</a>" ?>
                            <?php else: ?>
                                <?php $urlContaminants =  "fluoride" ?>
                            <?php endif;?>
                            <?php $last = '<li class="' . $_attributeCode . '">' . "The {$_product->getSku()} does not reduce {$urlContaminants}."  . '</li>' ?>
                            <?php continue; ?>
                        <?php endif; ?>
                        <?php if (!empty($valAtrr)): ?>
                            <li class="<?php echo $_attributeCode ?>">
                                <?php $attrUrl = $_helperLinksCatalog->getAttrContaminantsUrl($_attributeCode) ?>
                                <?php if ($valAtrr == 1): ?>
                                    <?php if (!empty($attrUrl)): ?>
                                        <a class="title" href="<?php echo Mage::getBaseUrl().$attrUrl ?>"><?php echo $_product->getResource()->getAttribute($_attributeCode)->getFrontendLabel()?> </a>
                                    <?php else: ?>
                                        <label class="title"><?php echo $_product->getResource()->getAttribute($_attributeCode)->getFrontendLabel()?> </label>
                                    <?php endif;?>
                                <?php else: ?>
                                    <label class="value"><?php echo $valAtrr . $this->__(' of ') ?></label>
                                    <?php if (!empty($attrUrl)): ?>
                                        <a class="title" href="<?php echo Mage::getBaseUrl().$attrUrl ?>"><?php echo $_product->getResource()->getAttribute($_attributeCode)->getFrontendLabel()?> </a>
                                    <?php else: ?>
                                        <label class="title"><?php echo $_product->getResource()->getAttribute($_attributeCode)->getFrontendLabel()?> </label>
                                    <?php endif;?>
                                <?php endif;?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if (!empty($last)): ?>
                        <?php echo $last ?>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>