<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php $subscription = $this->getSubscription(); ?>
<ul class="messages"></ul>
<?php echo $this->createChildSubscriptionBlock('subscription_info.phtml')->toHtml() ?>
<?php echo $this->createChildSubscriptionBlock('product_info.phtml')->toHtml() ?>
<?php echo $this->createChildSubscriptionBlock('actions.phtml')->toHtml() ?>
<div class="clearer"></div>
<?php if($this->getNextOrderDateMode() == SFC_Autoship_Model_System_Config_Source_Nextorderdatemode::MODE_MULTIPLE_DATES): ?>
<div class="subscription-more-details" style="display:none;" id="<?php echo $subscription->getSubscriptionId() ?>-more-details-div">
    <?php echo $this->createChildSubscriptionBlock('shipping_address.phtml')->toHtml() ?>
    <?php if ($this->showBillingAddressBlock()): ?>
    <?php echo $this->createChildSubscriptionBlock('billing_address.phtml')->toHtml() ?>
    <?php endif; ?>
    <?php echo $this->createChildSubscriptionBlock('payment.phtml')->toHtml() ?>
</div>
<div class="clearer"></div>
<?php endif; ?>