<?php
/***************************************************************************
 Extension Name	: Magento Navigation Menu Pro - Responsive Mega Menu / Accordion Menu / Smart Expand Menu
 Extension URL	: http://www.magebees.com/magento-navigation-menu-pro-responsive-mega-menu-accordion-menu-smart-expand.html
 Copyright		: Copyright (c) 2015 MageBees, http://www.magebees.com
 Support Email	: support@magebees.com 
 ***************************************************************************/ 
	$enable_disable = Mage::helper("navigationmenupro")->isEnabled();
	if($enable_disable == "1") {
	$groupId = $this->getGroupId();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/navigationmenupro/group-'.$groupId.'.css');?>" media="all" />
<?php
	$groupId = $this->getGroupId();
	$menu_customer = Mage::getModel('navigationmenupro/customer');
	$permission = $menu_customer->getUserPermission();
	$menu_type = $this->getMenutype($groupId);
	$developer_mode_enable_disable = Mage::helper("navigationmenupro")->isDevelopmentEnabled();
	if($developer_mode_enable_disable == "1") {
		echo $menu_html = Mage::helper("navigationmenupro")->get_menu_items($groupId);
	}else
	{
		echo $menu_html = Mage::helper("navigationmenupro")->getStaticMenu($groupId);
	}
	if($menu_type == "list-item") {
	/* Below Active code is use only when menu type is list-item other active code is added into the menu.js file*/
?>
<script>
jQuery(document).ready(function() {
	var group_id = 'cwsMenu-'+'<?php echo $groupId;?>';
	var pathname = window.location.pathname; // Returns path only
	var url      = window.location.href;  
	/* Make Current Menu Active After page is load using the page URL compare with the a href URL*/	
	jQuery(".cwsMenu li").removeClass("active");
	jQuery("a[href~='"+url+"']").parents().addClass("active");
	/* Add Active Class for the Top Level Li*/
	var topListItem = jQuery("#"+group_id+" li .active").parents('li').addClass('active');
	/* Add Active Class for all Sub Level Li*/
	var allListItem = jQuery(".active").parents("#"+group_id+" ul > li").addClass('active');
	
});
</script>
<?php 
}else
{?><script>
	jQuery(document).ready(function() {
		var group_id = 'cwsMenu-'+'<?php echo $groupId;?>';
		var pathname = window.location.pathname; // Returns path only
		var url      = window.location.href; 
		/* Make Current Menu Active After page is load using the page URL compare with the a href URL*/	
		jQuery(".cwsMenu li").removeClass("active");
		jQuery("a[href~='"+url+"']").parents().addClass("active");
	});
	</script>
<?php
}
}
?>

