<?php $suffix = strtolower($this->getNameInLayout()); ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget-catalogsale-products-carousel" id="<?php echo $suffix ?>">
<div class="page-title category-title">
		<h1>Special Products</h1>
	<div class="new-carousel-button">
		<a id="prev_sale" class="prev_sale sale_carousel_button" href="#"><span class="fa fa-angle-left"></span></a>
		<a id="next_sale" class="next_sale sale_carousel_button" href="#"><span class="fa fa-angle-right"></span></a>
	</div>
</div>
	  <div class="new-slider">
			  <div class="box-top">
				<ul id="sale-carousel" class="products-grid">
					<?php foreach ($_products->getItems() as $_product): ?>
					<li class="item">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/></a>
						<div class="product-details">
							<?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
							<p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)">
								<?php $product_name_carousel = strip_tags($_product->getName());
								 if (strlen($product_name_carousel) < 25) echo($product_name_carousel);
								 else { echo mb_substr($product_name_carousel, 0, 25,'UTF-8').'...';} ?>
							</a></p>
							<div class="desc_grid" itemprop="description"><?php $small_getDescription = strip_tags($_product->getShortDescription());
								 if (strlen($small_getDescription) < 60) echo($small_getDescription);
								 else { echo mb_substr($small_getDescription, 0, 60,'UTF-8').'...';} ?></div>
							<?php if ($_product->getIsSalable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span class="fa fa-shopping-cart"></span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="tooltip" class="link-wishlist my-button"><span class="fa fa-star"></span></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									<li><span class="separator">|</span> <a  title="<?php echo $this->__('Add to Compare') ?> " href="<?php echo $_compareUrl ?>" rel="tooltip" class="link-compare my-button"><span class="fa fa-compress"></span></a></li>
								<?php endif; ?>
							</ul>
							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
						</div>
						<div class="label-product">             
                            <?php if($_products->getData('new')){echo '<span class="new">'.$this->__('New!').'</span>';  }?>
                            <?php if($_products->getData('sale')){echo '<span class="sale">'.$this->__('Sale!').'</span>';  }?>
                        </div>

					</li>
					<?php endforeach ?>
				</ul>
				  <div class="clear"></div>
			  </div>
			 <div class="clear"></div>
	  </div>
</div>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#sale-carousel').carouFredSel({
			responsive: true,
			width: '100%',
			scroll: 1,
			auto : {
				play : 1,
				timeoutDuration :5000
			},
			items: {
				visible: {
					min:1,
					max:2,
					minimum: 1
				},
				minimum: 1,
				width: 270,
				height:  'variable' //451
			},
			mousewheel: true,
			swipe: {
				onMouse: true,
				onTouch: true
			},
			/*pagination: {
				container: ".carousel-pagination2",
			},*/
			prev: {
				button: "#prev_sale",
			},
			next: {
				button: "#next_sale",
			}
		});
	});
</script>

<?php endif; ?>

