<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */

?>
<?php if ($this->isAmazonPayButtonEnabled()): ?>

  <div id="<?php echo $this->getAmazonPayButtonId(); ?>" class="amazon-pay-button" style="margin-bottom:10px;"></div>

  <script type="text/javascript">
    var authRequest;

    var AmazonButtonOptions = {
        type: "<?php echo $this->getButtonType(); ?>",
        color: "<?php echo $this->getButtonColor(); ?>",
        size: "<?php echo $this->getButtonSize(); ?>",
        authorization: function() {
            loginOptions = {
                scope: "profile payments:widget payments:shipping_address<?php print $this->getAdditionalScope(); ?>",
                response_type: 'token',
                popup: <?php print $this->isPopup(); ?>
            };

            authRequest = amazon.Login.authorize (loginOptions, "<?php echo (!$this->isPopup()) ? $this->getLoginAuthUrl() : $this->getCheckoutUrl(); ?>");
        },
        onError: function(error) {
            console.log(error);
        }
    };

    OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);

    <?php
    /**
     * Google Analytics Enhanced Ecommerce Product Click Function
     */
    ?>
    jQuery( "#<?php echo $this->getAmazonPayButtonId(); ?>" ).click(function() {
        try {
            ga('send', 'event', 'UX', 'click', 'click to <?php echo $this->getAmazonPayButtonId(); ?>');
        } catch (e) {}
    });
  </script>

<?php endif; ?>