<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of SUBSCRIBE PRO INC.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@subscribepro.com>
 * @copyright 2009-2016 SUBSCRIBE PRO INC. All Rights Reserved.
 * @license   http://www.subscribepro.com/terms-of-service/ Subscribe Pro Terms of Service
 * @link      http://www.subscribepro.com/
 *
 */
?>
<?php if ($this->showJsonp()): ?>
    <script type="text/javascript">
        var jsonpEnvironmentKey = "<?php echo $this->getEnvironmentKey() ?>";
        var jsonpUrl = "<?php echo $this->getJSONPUrl() ?>";
    </script>
<?php endif; ?>
