<?php echo $this->getCategoryFooterJs(); ?>
<script type="text/javascript">
//<![CDATA[
	var OGControllerCategoryProductAddToCart = function(productId) {
		//Own Product business logic disabled general category product add to cart
		//However, acne product is implemented as catagory
//		if(OG != undefined && OG.Controller != undefined){
//			//alert('OG category product add to cart logic, product id: #' + productId);
//			OG.Controller.categoryProductAddToCart(productId);
//		}
	};
//]]>
</script>