<?php if ($posts = $this->getRecent()): ?>
    <div class="blog-bg" data-source-url="skin url='images/blog-bg.jpg">
        <div class="widget-latest">
            <div class="page-title category-title center">
                <h1><?php echo Mage::helper('blog')->__('Latest Posts');  ?></h1>
            </div>
                <?php $i = 0; ?>
            <div class="blog-carousel owl-carousel">
                <?php foreach ($posts as $post): ?>
                    <?php if ($i<3): ?>
                                    <?php $_ct= new Zend_Date($post->getCreatedTime()); ?>
                            <div class="col-item3 blog_item">
                                <div class="blog-wrapper">
                                    <div class="postContent aw_image"><?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($post->getShortContent()); ?></div>
                                    <span class="widget-latest-data"><?php echo $_ct->toString('dd.MM.yyyy'); ?></span>
                                    <div class="widget-latest-title"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></div>
                                    <div class="postContent aw_text"><?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($post->getShortContent()); ?></div>
                                    <div class="widget-latest-details">
                                        <?php // $post->setCreatedTime($this->formatDate($post->getCreatedTime(), "long", false)); ?>
                                        <?php //echo $post->getCreatedTime(); ?>
                                    </div>
                                    <div class="blog_bottom_block">
                                        <a href="<?php echo $post->getAddress(); ?>"class="aw-blog-read-more all-blog button"><span><?php echo Mage::helper('blog')->__('Read more');  ?></span></a>
                                        <a class="widget-latest-comment" href="<?php echo $post->getAddress(); ?>#commentBox" >
                                             <i class="fa fa-comment"></i>
                                            <?php if ($post->getCommentCount() > 0): ?>
                                                <?php echo $post->getCommentCount(); ?>
                                            <?php endif; ?>
                                             <?php if ($post->getCommentCount() < 1): ?> 
                                                <?php echo "0"; ?>
                                            <?php endif; ?>
                                        </a>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>
                    <?php endif; ?>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </div>
           <!-- <a href="<?php // echo $this->getBlogUrl() ?>"class="aw-blog-read-more all-blog"><?php // echo Mage::helper('blog')->__('View all posts');  ?></a> -->
        </div>
    </div>
<?php endif; ?>
<script>
    jQuery(document).ready(function() {
 
  jQuery(".blog-carousel").owlCarousel({
    singleItem : false,
    items: 1,
    autoPlay : true,
    navigation : true,
    responsive: true,
    navigationText : false,
    itemsDesktop: [1199,1],
    itemsDesktopSmall: [979,1],
    itemsTablet: [767,2],
    itemsTabletSmall: false,
    itemsMobile: [479,1]
  });
 
});
</script>
<?php // $tt = count($this->getRecent()); print_r($tt) ; ?>
