<?php
/**
 * Subscribe Pro - Subscriptions Management Extension
 *
 * PHP version 5
 *
 * LICENSE: This source file is subject to commercial source code license of StoreFront Consulting, Inc.
 *
 * @category  SFC
 * @package   SFC_Autoship
 * @author    Garth Brantley <garth@storefrontconsulting.com>
 * @author    Dennis Rogers <dennis@storefrontconsulting.com>
 * @copyright 2009-2013 StoreFront Consulting, Inc. All Rights Reserved.
 * @license   http://www.storefrontconsulting.com/media/downloads/ExtensionLicense.pdf StoreFront Consulting Commercial License
 * @link      http://www.storefrontconsulting.com/autoship-subscriptions-and-recurring-billing-magento-extension/
 *
 */
?>
<?php $configValue = Mage::getStoreConfig('web/hotdeals/hotdeal_link_param');
$hotDeal = Mage::registry('hotdeal'); ?>
<?php //if(!($this->getRequest()->getParam($configValue)) && !$hotDeal ): //no subscriptions with the HotDeal ?>
<?php if(Mage::getStoreConfig('autoship_general/general/enabled') == '1'): ?>
<?php if($this->isProductAutoshipEligible()): ?>
<?php $variableArray = array(
          'ourPrice' => $this->getOneTimePurchasePrice(true),
          'subscrPrice' => substr($this->getDiscountText(), 0, -31)
      );
      echo  Mage::helper('usff/data')->setVariableInCmsBlock($variableArray, 'subscription_price');
?>
<script type="text/javascript">
    addEvent(window, 'load', function(){
        $$('a.fireBtn').invoke('observe', 'click', function(e) {
            $('subscrPopUp').show();
            e.preventDefault();
        });
        if ($('popUpClose')) {
        $('popUpClose').observe('click', function(e) {
            $('subscrPopUp').hide();
        });
        }
    });
</script>

<div class="subscription-product hidden">
<ul class="options-list" id="idToCheckIfExists">
    <li>
		<input type="radio" class="radio" id="delivery-option-one-time" name="delivery-option" value="one-time-delivery" checked="checked"/>
		<input type="radio" class="radio" id="delivery-option-subscribe" name="delivery-option" value="subscribe"/>
        <input type="hidden" name="delivery-interval" value="Monthly"/>
    </li>
</ul>
</div>
<?php if(Mage::getStoreConfig('autoship_subscription/subscription/use_new_subscription_page') == '1'): ?>
<script type="text/javascript">
//<![CDATA[
addEvent(window, 'load', function() {
    $j = jQuery;
    $j(document).ready(function () {
        toggleAddToCart();
        $j('input[name=delivery-option]').bind('change', function () {
            toggleAddToCart();
        });
        $j('#subscribe_button').bind('click', function (e) {
            e.preventDefault();
            window.location = '<?php echo $this->getUrl('autoship/newsubscription/index') ?>product_id/<?php echo $this->getProduct()->getId() ?>/qty/' + $j('#qty').val() + '/interval/' + $j('#delivery-interval').val() + '/';
        });
    });
    function toggleAddToCart() {
        if ($j('#delivery-option-one-time').is(':checked')) {
            $j('#add_to_cart').show();
            $j('#subscribe').hide();
        } else {
            $j('#add_to_cart').hide();
            $j('#subscribe').show();
        }
    }
});
//]]>
</script>
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>
<?php //endif; ?>
