<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento ENTERPRISE edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.2.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 */
?>
<?php
    ?>
<?php if($this->getProductData()->getId()): ?>
<div class="product-review">
    <div class="page-title">
        <h1><?php echo $this->__('Review Details') ?></h1>
    </div>
    <div class="product-img-box">
        <a href="<?php echo $this->getProductData()->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(285, 285); ?>" height="285" width="285" alt="<?php echo $this->escapeHtml($this->getProductData()->getName()) ?>" class="product-image" /></a>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
          <p><?php echo $this->__('Average Customer Rating') ?>:</p>
          <?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
        <?php endif; ?>
    </div>
    <div class="details">
        <h3 class="product-name"><?php echo $this->escapeHtml($this->getProductData()->getName()) ?></h3>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
            <h4><?php echo $this->__('Product Rating:') ?></h4>

            <table class="data-table review-summary-table">
            <?php foreach ($this->getRating() as $_rating): ?>
            <?php if($_rating->getPercent()): ?>
                <tr>
                    <td class="label"><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></td>
                    <td class="value">
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                        </div></td>
                </tr>
            <?php endif; ?>
            <?php endforeach; ?>
            </table>
        <?php endif; ?>
        <p class="date"><?php echo $this->__('Product Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?></p>
        <p><?php echo nl2br($this->escapeHtml($this->getReviewData()->getDetail())) ?></p>
        <?php
            echo $this->getChild('advancedreviews_proscons_indicator')->setReviewId( $this->getReviewData()->getId() )->toHtml();
            echo $this->getChild('advancedreviews_recommend_indicator')->setReviewId( $this->getReviewData()->getId() )->toHtml();
            echo $this->getChild('advancedreviews_footer')->setReviewId( $this->getReviewData()->getId() )->toHtml();
        ?>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getProductData()->getProductUrl(); //$this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Product Reviews') ?></a></p>
    </div>
</div>
<?php endif; ?>
