<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento ENTERPRISE edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento ENTERPRISE edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.2.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-ENTERPRISE.txt
 */
?>
<?php
?>
<?php if ( $this->canShow() ): ?>
    <li>
        <label for="nickname_field"><?php echo $this->__('Would you recommend this product to a friend?') ?></label>
        <div class="input-box">
            <select name="recommend"  id="recommend_field" class="input-text" style="width: 420px;">
                <option></option>
                <?php foreach ( $this->getOptions() as $option ): ?>
                <option value="<?php echo $option['value'] ?>"><?php echo $this->__($option['label']) ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
<?php endif; ?>