<?php 
if (Mage::getStoreConfig('specialpricecountdown/general/active', Mage::app()->getStore())):	

	$tm_specialpricecountdown_settings = array(
		'selector' 			=> Mage::getStoreConfig('specialpricecountdown/general/selector', Mage::app()->getStore()),
		);
	?>  

	<script>
		jQuery(document).ready(function(){
			var anchor_selector = jQuery("<?php echo $tm_specialpricecountdown_settings['selector']; ?>");
			anchor_selector.after('<div id="special_countdown"></div>');

		    var clock = jQuery('#special_countdown').FlipClock(<?php echo Mage::helper('specialpricecountdown/data')->countdownTime(); ?>, {
		        clockFace: 'DailyCounter',
		        countdown: true
		    });
	    })
	</script>
<?php endif; ?>