<!--Best Selling-->
<?php

$totalPerPage = ($this->show_total) ? $this->show_total : 6;
$counter = 1;
$visibility = array(
Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);

$storeId = Mage::app()->getStore()->getId();

$_productCollection = Mage::getResourceModel('reports/product_collection')
->addAttributeToSelect('*')
->addOrderedQty()
//->addAttributeToFilter('visibility', $visibility)
->setOrder('ordered_qty', 'desc');

$total = Mage::getStoreConfig('catalog/best_selling/total');
$i=0;

?>

<div class="bx-slider-sel">
<div class="homepage-label">
    <h3 class="homepage-title">BEST SELLING</h3>
    <h6>Shop Products</h6>
</div>
<div id="gallery-wrap1">
    <ul id="gallery1">
    <?php foreach($_productCollection as $_product): ?>
    <?php if($total =='' || $i<$total):?>
    <li>
        <?php //var_dump($_product);die();?>
            <div class="item">
                <?php
                    $_product_new = Mage::getModel('catalog/product')->load($_product->getId());

                    if($_product_new->getSpecial_from_date() &&  $_product_new->getSpecial_to_date()) :
                        $date_from_price = strtotime($this->formatDate($_product_new->getSpecial_from_date()));
                        $date_to_price = strtotime($this->formatDate($_product_new->getSpecial_to_date()));
                        $date_current_price = strtotime(date('m/d/y'));

                ?>
                        <?php if($date_from_price <= $date_current_price && $date_to_price >= $date_current_price && $_product->getSpecialPrice() != null): ?>
                    <span class="date-sale">
                        <img src="<?php echo $this->getSkinUrl()?>images/icon-sale.png" />
                    </span>
                        <?php endif; ?>
                    <?php elseif($_product->getSpecialPrice() != null): ?>
                        <span class="date-sale">
                        <img src="<?php echo $this->getSkinUrl()?>images/icon-sale.png" />
                        </span>
                    <?php endif; ?>
                <div class="item-inner">
                    <a href="<?php echo $_product_new->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product_new, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product_new, 'small_image')->resize(135); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product_new, 'small_image'), null, true) ?>" /></a>
                    <h2 class="product-name"><a href="<?php echo $_product_new->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php
                        $productName=$_product->getData('order_items_name');
                            if(strlen($productName)>60){
                                echo substr($productName,0,60). ' ...';
                            }
                            else
                                echo $productName;
                    ?></a>

                    </h2>
                    <?php echo $this->getPriceHtml($_product_new, true) ?>
                    <?php if($_product_new->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product_new, 'short') ?>
                    <?php endif; ?>
                    <div class="actions">
                        <?php if($_product_new->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product_new) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
    </li>
    <?php
        $i++;
        endif;
        endforeach;
    ?>
    </ul>
</div>


<div id="gallery-controls1">
    <a href="#" id="gallery-prev1">&lt;</a>
    <a href="#" id="gallery-next1">&gt;</a>
</div>
</div>
<script type="text/javascript">
    addEvent(window, 'load', function() {

        // Gallery
        if(jQuery("#gallery1").length){
            // Declare variables
            var totalImages = jQuery("#gallery1 > li").length,
                    imageWidth = jQuery("#gallery1 > li:first").outerWidth(true),
                    totalWidth = (imageWidth+1) * totalImages,
                    visibleImages = Math.round(jQuery("#gallery-wrap1").width() / imageWidth),
                    visibleWidth = visibleImages * imageWidth,
                    stopPosition = (visibleWidth - totalWidth);

            jQuery("#gallery1").width(totalWidth);

            jQuery("#gallery-prev1").click(function(){
                if(jQuery("#gallery1").position().left < 0 && !jQuery("#gallery1").is(":animated")){
                    jQuery("#gallery1").animate({left : "+=" + (imageWidth+1) + "px"});
                }
                return false;
            });

            jQuery("#gallery-next1").click(function(){
                if(jQuery("#gallery1").position().left > stopPosition && !jQuery("#gallery1").is(":animated")){
                    jQuery("#gallery1").animate({left : "-=" + (imageWidth+1) + "px"});
                }
                return false;
            });
        }

    });
</script>
